const projetos = [
  {
    id: "bipagem-manifesto-minuta",
    categoria: "web",
    nome: "Sistema de Bipagem — Rastreio de Manifesto e Minuta",
    nomeEn: "Barcode Scanning System — Manifest & Freight Note Tracking",
    descricao: "Sistema operacional de bipagem que rastreia em tempo real todos os itens de manifesto e minuta, identificando o status de picking de cada volume: previsto x realizado, por quem e onde foi bipado.",
    descricaoEn: "Operational barcode scanning system that tracks in real time all manifest and freight note items, identifying the picking status of each volume: planned vs actual, who scanned it and where.",
    descricaoCompleta: "Plataforma de controle operacional desenvolvida para garantir rastreabilidade total da carga. O sistema identifica cada item registrado em um manifesto ou minuta e verifica se o picking foi realizado ou não, registrando o usuário responsável e o ponto de bipagem. A visão de Previsto x Realizado permite ao gestor operacional identificar divergências em tempo real e agir antes que cargas sejam expedidas com pendências. O sistema elimina auditorias manuais e reduz drasticamente as divergências de carregamento.",
    descricaoCompletaEn: "Operational control platform built to ensure full cargo traceability. The system identifies each item registered in a manifest or freight note and checks whether picking was performed or not, recording the responsible user and scanning point. The Planned vs Actual view enables operations managers to identify discrepancies in real time and act before loads are shipped with pending items. The system eliminates manual audits and drastically reduces loading discrepancies.",
    atuacao: "Desenvolvi a lógica de rastreio item a item com cruzamento de dados entre manifesto, minuta e registros de bipagem. Implementei a visão consolidada de Previsto x Realizado com indicadores de status por volume (bipado/não bipado), identificação de operador e localização de bipagem. O sistema suporta consulta por manifesto, motorista ou rota, fornecendo visibilidade completa sobre o ciclo de carregamento e permitindo auditorias automáticas pré-expedição.",
    atuacaoEn: "Developed item-by-item tracking logic by crossing manifest, freight note and scanning records. Implemented a consolidated Planned vs Actual view with per-volume status indicators (scanned/not scanned), operator identification and scan location. The system supports queries by manifest, driver or route, providing complete visibility over the loading cycle and enabling automatic pre-dispatch audits.",
    tecnologias: ["Next.js", "TypeScript", "PostgreSQL", "Prisma ORM", "Real-time Monitoring", "Logistics"],
    imagem: "assets/projetos/bipagem_manifesto.png",
    imagemReal: false,
    classeFiltro: "brightness-110",
    github: null
  },
  {
    id: "sistema-obras-ia",
    categoria: "web",
    nome: "Sistema Inteligente de Gestão de Obras com IA",
    nomeEn: "Intelligent Construction Management System with AI",
    descricao: "Plataforma de gestão de obras com IA que sugere escopos baseados em projetos similares próximos, além de controle total de materiais, orçamento e progresso da construção.",
    descricaoEn: "Construction management platform with AI that suggests project scopes based on similar nearby completed builds, plus full control over materials, budget, and construction progress.",
    descricaoCompleta: "Sistema focado em engenharia civil e gestão de obras que combina Inteligência Artificial com controle operacional completo. A IA analisa obras já realizadas em terrenos próximos e com metragem semelhante, gerando automaticamente um escopo sugerido de materiais, etapas e estimativas de custo para o engenheiro civil e o mestre de obras. Além da assistência inteligente no planejamento, o sistema oferece controle total da execução: gestão de compras de materiais, controle do estoque consumido x disponível, registro de fornecedores, acompanhamento de orçamento e relatórios de progresso físico-financeiro da obra.",
    descricaoCompletaEn: "System focused on civil engineering and construction management that combines Artificial Intelligence with full operational control. The AI analyzes completed builds on nearby lots with similar size, automatically generating a suggested scope of materials, stages, and cost estimates for the civil engineer and site foreman. Beyond intelligent planning assistance, the system provides full execution control: material purchasing management, consumed vs available stock control, supplier records, budget tracking, and physical-financial progress reports.",
    atuacao: "Arquitetei e desenvolvi a plataforma end-to-end. Implementei o módulo de IA para sugestão de escopo com base em geolocalização e metragem de terreno, cruzando com histórico de obras cadastradas. Desenvolvi os módulos de controle de materiais (comprado x gasto x estoque), gestão de fornecedores, controle orçamentário e relatórios de progresso físico-financeiro. O sistema permite que engenheiros e mestres de obras tenham visibilidade total do projeto desde o planejamento até a entrega.",
    atuacaoEn: "Architected and developed the end-to-end platform. Implemented the AI scope suggestion module based on geolocation and lot size, crossed with historical build data. Developed material control modules (purchased vs spent vs stock), supplier management, budget control, and physical-financial progress reports. The system gives engineers and site foremen full visibility from planning to delivery.",
    tecnologias: ["Next.js", "TypeScript", "PostgreSQL", "OpenAI API", "Geolocation", "Prisma ORM", "BI"],
    imagem: "assets/projetos/sistema_obras.png",
    imagemReal: false,
    classeFiltro: "brightness-105",
    github: null
  },
  {
    id: "n8n-chatbot-atendimento",
    categoria: "dados",
    nome: "Automação de Atendimento Inteligente com N8N",
    nomeEn: "Intelligent Customer Service Automation with N8N",
    descricao: "Correção e evolução de fluxo de atendimento via WhatsApp com IA, integrando detecção de atendimento humano ativo e agrupamento inteligente de mensagens.",
    descricaoEn: "Correction and evolution of WhatsApp AI customer service flow, integrating active human takeover detection and intelligent message grouping.",
    descricaoCompleta: "Consultoria técnica e desenvolvimento em fluxo de atendimento automatizado via WhatsApp utilizando N8N. O cliente operava com IA respondendo via ChatGPT 4.1 integrada ao Kommo CRM para 4 clientes, enfrentando dois problemas críticos: a IA continuava respondendo mesmo quando um atendente humano assumia a conversa, e também respondia cada mensagem curta individualmente ao invés de aguardar e consolidar o contexto completo. O projeto envolveu reestruturação do fluxo (Webhook → Supabase → verificação de status de transferência → identificação de tipo de mensagem → análise → agente LLM) e refinamento de prompt para corrigir os comportamentos indesejados.",
    descricaoCompletaEn: "Technical consulting and development on an automated WhatsApp customer service flow using N8N. The client operated with ChatGPT 4.1 integrated into Kommo CRM for 4 clients, facing two critical issues: the AI kept responding even when a human agent took over, and it replied to each short message individually instead of waiting and consolidating context. The project involved restructuring the flow (Webhook → Supabase → transfer status check → message type detection → analysis → LLM agent) and prompt engineering to fix unwanted behaviors.",
    atuacao: "Diagnostiquei e corrigi dois problemas críticos no fluxo: (1) Implementei lógica de detecção de atendimento humano ativo — o sistema agora verifica no Supabase se há flag de transferência ativa antes de permitir que a IA processe e responda; (2) Implementei agrupamento de mensagens em sequência — via controle de tempo/buffer, mensagens enviadas em rajada são consolidadas em um único contexto antes de acionar o agente. Além disso, revisei e otimizei o prompt do agente para eliminar respostas fora da base de conhecimento, garantindo respostas mais precisas e dentro do escopo definido.",
    atuacaoEn: "Diagnosed and fixed two critical flow issues: (1) Implemented active human takeover detection — the system now checks Supabase for an active transfer flag before allowing the AI to process and respond; (2) Implemented sequential message grouping — via time/buffer control, burst messages are consolidated into a single context before triggering the agent. Also reviewed and optimized the agent prompt to eliminate out-of-scope responses, ensuring more accurate answers within the defined knowledge base.",
    tecnologias: ["N8N", "ChatGPT 4.1", "Supabase", "PostgreSQL", "ZAPI", "WhatsApp API", "Prompt Engineering"],
    imagem: "assets/projetos/n8n_chatbot.png",
    imagemReal: true,
    classeFiltro: "brightness-110",
    github: null
  },
  {
    id: "tcc-visao-computacional-epi",
    categoria: "academico",
    nome: "TCC — Sistema Inteligente de Monitoramento de EPIs com Visão Computacional",
    nomeEn: "Senior Thesis — Intelligent EPI Monitoring System with Computer Vision",
    descricao: "Sistema de Visão Computacional para identificação automática de EPIs em ambientes industriais, aprovado com nota máxima (10). Arquitetura YOLOv8 com precisão de até 99%.",
    descricaoEn: "Computer Vision system for automatic EPI detection in industrial environments, awarded top grade (10). YOLOv8 architecture with up to 99% precision.",
    descricaoCompleta: "Trabalho de Conclusão de Curso em Engenharia de Software aprovado com nota 10. O projeto desenvolveu um Sistema Inteligente de Monitoramento de EPIs (Equipamentos de Proteção Individual) para Ambientes Industriais, utilizando Visão Computacional e Inteligência Artificial. A arquitetura é baseada em YOLOv8, implementado em Python, com integração a MongoDB para armazenamento de dados de detecção e dashboards de Business Intelligence para acompanhamento em tempo real. O sistema identifica automaticamente o uso correto de capacetes, coletes e óculos de proteção, contribuindo diretamente para a prevenção de acidentes e apoio à tomada de decisão em ambientes industriais. Resultados: precisão de até 99% em base autoral, mAP de 0,988 no primeiro treinamento e validação em base ampliada com mais de 7.300 imagens.",
    descricaoCompletaEn: "Software Engineering Senior Thesis awarded top grade (10). The project developed an Intelligent EPI (Personal Protective Equipment) Monitoring System for Industrial Environments using Computer Vision and Artificial Intelligence. The architecture is based on YOLOv8, implemented in Python, integrated with MongoDB for detection data storage and Business Intelligence dashboards for real-time tracking. The system automatically identifies correct use of helmets, vests and safety glasses, contributing directly to accident prevention and decision support in industrial environments. Results: up to 99% precision on authorial dataset, mAP of 0.988 on first training, and validation on an expanded dataset of over 7,300 images.",
    atuacao: "Conduzi o desenvolvimento completo do sistema: coleta e anotação do dataset autoral, treinamento do modelo YOLOv8 em Python, integração com MongoDB para persistência dos eventos de detecção, construção de dashboards de BI para análise gerencial e validação em base ampliada com mais de 7.300 imagens para garantir robustez e generalização. O trabalho reforça o potencial da IA aplicada à segurança do trabalho. Aprovado com nota máxima (10) pela banca avaliadora.",
    atuacaoEn: "Led the full system development: authorial dataset collection and annotation, YOLOv8 model training in Python, MongoDB integration for detection event persistence, BI dashboard construction for management analytics, and validation on an expanded dataset of 7,300+ images to ensure robustness and generalization. The work reinforces AI's potential applied to workplace safety. Awarded maximum grade (10) by the evaluation board.",
    tecnologias: ["YOLOv8", "Python", "Computer Vision", "MongoDB", "Business Intelligence", "Deep Learning"],
    imagem: "assets/projetos/tcc_epi.png",
    imagemReal: true,
    classeFiltro: "brightness-105",
    github: null
  },
  {
    id: "ia-logistica-wa",
    categoria: "dados",
    nome: "IA Generativa & Curadoria Logística",
    nomeEn: "Generative AI & Logistics Curation",
    descricao: "Solução de Inteligência Artificial para análise estratégica de movimentações logísticas e distribuição automatizada de insights via WhatsApp.",
    descricaoEn: "Artificial Intelligence solution for strategic analysis of logistics movements and automated insight distribution via WhatsApp.",
    descricaoCompleta: "Implementação de um ecossistema inteligente utilizando IA Generativa para otimizar o fluxo de informações executivas. O sistema realiza a coleta diária de dados de transferências logísticas, processa as informações através de modelos de linguagem (OpenAI) e orquestra a entrega de insights críticos diretamente para os grupos de gestão.",
    descricaoCompletaEn: "Implementation of an intelligent ecosystem using Generative AI to optimize executive information flow. The system gathers daily logistics transfer data, processes information via OpenAI language models, and orchestrates critical insight delivery directly to management groups.",
    atuacao: "Arquitetei o fluxo completo no n8n integrado à API da OpenAI. O sistema é responsável pela curadoria automatizada de dados operacionais, gerando pré-análises estratégicas que chegam via WhatsApp nas primeiras horas do dia. Resultado: Redução drástica na triagem manual e aceleração do processo decisório em até 50%.",
    atuacaoEn: "Architected the complete workflow in n8n integrated with OpenAI API. Automated operational data curation, delivering strategic pre-analyses via WhatsApp early morning. Result: Drastic manual screening reduction and up to 50% faster decision making.",
    tecnologias: ["n8n", "OpenAI API", "WhatsApp API", "Node.js", "Analytics"],
    imagem: "assets/projetos/ia_logistica.png",
    imagemReal: false,
    classeFiltro: "brightness-110",
    github: null
  },
  {
    id: "bi-agro-suinos",
    categoria: "dados",
    nome: "BI Analítico: Conversão Alimentar Suína",
    nomeEn: "Analytical BI: Swine Feed Conversion",
    descricao: "Plataforma de Business Intelligence para otimização nutricional e controle de custos no agronegócio.",
    descricaoEn: "Business Intelligence platform for nutritional optimization and cost control in agribusiness.",
    descricaoCompleta: "Desenvolvimento de uma solução analítica avançada voltada à nutrição animal. O projeto foca na correlação técnica entre níveis proteicos de rações e índices de conversão alimentar, permitindo uma visão científica sobre a eficiência produtiva.",
    descricaoCompletaEn: "Development of an advanced analytical solution focused on animal nutrition. Correlates feed protein levels with feed conversion ratios for scientific insights into production efficiency.",
    atuacao: "Realizei a modelagem de dados complexa e a criação de dashboards em Power BI. A ferramenta permite correlacionar a composição das rações com o desempenho animal, identificando fornecedores e matérias-primas mais eficientes. O projeto contribuiu para ganhos estimados de 15-20% na eficiência da análise gerencial e precisão nutricional.",
    atuacaoEn: "Performed complex data modeling and created Power BI dashboards. The tool correlates feed composition with animal performance, identifying more efficient suppliers and raw materials. Contributed to an estimated 15-20% gain in management analysis efficiency.",
    tecnologias: ["Power BI", "SQL Server", "MySQL", "Data Modeling", "AgroTech"],
    imagem: "assets/projetos/agro_nutricao.png",
    imagemReal: false,
    classeFiltro: "hue-rotate-15",
    github: null
  },
  {
    id: "data-arch-high",
    categoria: "dados",
    nome: "Arquitetura de Dados High Performance",
    nomeEn: "High-Performance Data Architecture",
    descricao: "Reestruturação de arquitetura cloud para processamento de alto volume e otimização de fluxos analíticos.",
    descricaoEn: "Cloud data architecture restructuring for high-volume processing and analytical workflow optimization.",
    descricaoCompleta: "Projeto de engenharia de dados focado em escalabilidade e performance. O desafio era reestruturar o pipeline de dados que sofria com gargalos de processamento, migrando de conexões diretas para uma arquitetura baseada em Power BI Service e Dataflows.",
    descricaoCompletaEn: "Data engineering project focused on scalability and performance. Restructured data pipelines plagued by processing bottlenecks, migrating to a Power BI Service and Dataflows architecture.",
    atuacao: "Liderei a migração de conexões AWS para Dataflows Gen1, implementando pipelines ETL/ELT otimizados. O resultado foi uma redução drástica no tempo de carregamento de dashboards, saindo de 8 horas para apenas 15 minutos, mesmo em bases com milhões de registros, garantindo estabilidade e governança dos dados.",
    atuacaoEn: "Led the migration from AWS connections to Dataflows Gen1, implementing optimized ETL/ELT pipelines. Reduced dashboard refresh time from 8 hours to just 15 minutes across millions of records.",
    tecnologias: ["Power BI Service", "Dataflows", "AWS Cloud", "ETL/ELT", "Performance Tuning"],
    imagem: "assets/projetos/arquitetura_cloud.png",
    imagemReal: false,
    classeFiltro: "saturate-150",
    github: null
  },
  {
    id: "dgh-torre",
    categoria: "web",
    nome: "Sistema DGH — Torre de Controle Operacional",
    nomeEn: "DGH System — Operational Control Tower",
    descricao: "Sistema full stack para gestão de frota, telemetria e análise de comportamento de motoristas em tempo real.",
    descricaoEn: "Full-stack fleet management system with telemetry and real-time driver behavior analysis.",
    descricaoCompleta: "Desenvolvimento de uma plataforma corporativa centralizada para monitoramento de performance operacional. O sistema integra dados de telemetria para fornecer uma visão 360º da frota, focando na segurança e redução de riscos operacionais.",
    descricaoCompletaEn: "Centralized corporate platform development for monitoring operational performance. Integrates telemetry data for a 360º fleet view, enhancing safety and reducing operational risks.",
    atuacao: "Desenvolvi a arquitetura full stack e implementei módulos inteligentes de monitoramento (excesso de velocidade, motor ocioso, direção agressiva). Estruturei a identificação automatizada de motoristas via cruzamento de escalas operacionais e dashboards executivos para apoio à tomada de decisão imediata.",
    atuacaoEn: "Developed full-stack architecture and intelligent monitoring modules (speeding, idling, harsh driving). Automated driver identification by matching shift schedules with real-time telemetry.",
    tecnologias: ["Next.js", "TypeScript", "PostgreSQL", "Prisma ORM", "tRPC", "Tailwind CSS"],
    imagem: "assets/projetos/dgh.png",
    imagemReal: false,
    classeFiltro: "contrast-125",
    github: null
  },
  {
    id: "transf-logistica",
    categoria: "web",
    nome: "Torre de Controle — Transferência Logística",
    nomeEn: "Control Tower — Logistics Transfer",
    descricao: "Monitoramento em tempo real de cargas e análise preditiva de atrasos.",
    descricaoEn: "Real-time cargo tracking and predictive delay analytics.",
    descricaoCompleta: "Monitoramento logístico em tempo real com integração de telemetria GPS (Sascar).",
    descricaoCompletaEn: "Real-time logistics monitoring integrated with Sascar GPS telemetry.",
    atuacao: "Dashboards em tempo real, mapas interativos e sincronização de dados GPS.",
    atuacaoEn: "Real-time dashboards, interactive maps, and GPS data synchronization.",
    tecnologias: ["Next.js", "TypeScript", "Leaflet", "PostgreSQL", "Prisma ORM"],
    imagem: "assets/projetos/logistica.png",
    imagemReal: false,
    classeFiltro: "brightness-90",
    github: null
  },
  {
    id: "gestao-socorro",
    categoria: "web",
    nome: "Sistema Inteligente de Resposta a Incidentes",
    nomeEn: "Intelligent Incident Response System",
    descricao: "Solução de geolocalização e Service Desk para otimização de socorro mecânico e redução de tempos de resposta.",
    descricaoEn: "Geolocation and Service Desk solution to optimize breakdown assistance and cut response times.",
    descricaoCompleta: "Plataforma voltada à gestão de ocorrências e incidentes de frota. Utiliza inteligência geográfica para automatizar a logística de socorro, garantindo agilidade em situações críticas.",
    descricaoCompletaEn: "Fleet incident management platform leveraging spatial intelligence to automate roadside assistance dispatching.",
    atuacao: "Implementei a lógica de proximidade baseada em cálculos geoespaciais, permitindo a identificação automática da base de socorro mais próxima. Resultado: Redução estimada entre 25% e 35% no tempo médio de resposta a ocorrências, aumentando significativamente a eficiência operacional em campo.",
    atuacaoEn: "Implemented geospatial proximity algorithms to auto-select the nearest response base. Resulted in a 25-35% reduction in average incident response time.",
    tecnologias: ["Next.js", "PostgreSQL", "Geospatial Logic", "RBAC", "Service Desk"],
    imagem: "assets/projetos/socorro.png",
    imagemReal: false,
    classeFiltro: "sepia-25",
    github: null
  },
  {
    id: "auditoria-picking",
    categoria: "dados",
    nome: "Control Tower — Auditoria de Picking e Bipagem",
    nomeEn: "Control Tower — Picking Audit & Barcode Scanning",
    descricao: "Sistema de auditoria operacional e BI para rastreabilidade de cargas e redução de divergências logísticas.",
    descricaoEn: "Operational audit system and BI for cargo traceability and reduction of logistics discrepancies.",
    descricaoCompleta: "Solução de Business Intelligence desenvolvida para monitorar o ciclo de movimentação de mercadorias. O foco é a auditoria em tempo real dos processos de picking e transbordo para eliminar falhas no carregamento.",
    descricaoCompletaEn: "Business Intelligence solution designed to monitor cargo lifecycle. Focuses on real-time picking and transshipment audit to prevent loading errors.",
    atuacao: "Criei dashboards operacionais e implementei consultas SQL avançadas com CTEs para consolidação analítica de alto volume. O sistema permitiu a identificação imediata de pendências e volumes em transbordo, garantindo performance e confiabilidade analítica total sobre a operação de carga.",
    atuacaoEn: "Created operational dashboards and advanced SQL CTEs for high-volume analytical consolidation. Enabled immediate identification of pending items and transshipment volumes.",
    tecnologias: ["Next.js", "SQL Avançado", "PostgreSQL", "Data Audit", "Real-time Monitoring"],
    imagem: "assets/projetos/auditoria.png",
    imagemReal: false,
    classeFiltro: "grayscale-0",
    github: null
  },
  {
    id: "project-flow",
    categoria: "web",
    nome: "ProjectFlow — Gestão de Projetos",
    nomeEn: "ProjectFlow — Project Management",
    descricao: "Ecossistema completo para gestão de cronogramas, tarefas, análise de riscos e produtividade de equipes.",
    descricaoEn: "Complete ecosystem for schedule management, tasks, risk analysis, and team productivity.",
    descricaoCompleta: "Desenvolvimento de uma plataforma moderna focada no ciclo de vida de projetos. O sistema oferece ferramentas de gestão ágil e análise estratégica para controle de prazos e performance.",
    descricaoCompletaEn: "Modern project lifecycle management platform offering agile tools and strategic analytics for timeline and performance control.",
    atuacao: "Arquitetei a aplicação e modelei o banco de dados. Implementei funcionalidades avançadas como quadro Kanban, timelines visuais e ferramentas de análise estratégica (SWOT, 5W2H e análise de causa raiz). O sistema provê acompanhamento consolidado de progresso e gestão de riscos em tempo real.",
    atuacaoEn: "Architected application and database schema. Implemented Kanban boards, interactive timelines, and strategic tools (SWOT, 5W2H, Root Cause Analysis).",
    tecnologias: ["Next.js", "TypeScript", "Prisma ORM", "Zustand", "Recharts", "Mermaid.js"],
    imagem: "assets/projetos/projectflow.png",
    imagemReal: true,
    classeFiltro: "invert-0",
    github: null
  }
];
